services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/chat_db?schema=public"
      JWT_SECRET: "seu_seguro_jwt"
    restart: always

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: chat_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: